### ISSUE TITLE
Problem with authorising with ADFS API Token

### ISSUE THREAD

**Issue by evgenii-spec** [MicrosoftDocs/windows-itpro-docs#11677]
Hello,
Successfully getting token from ADFS with client id and secret for Dynamics CRM API.
Problem that after getting token i receive access denied.
From Event Viewer in ADFS it shows such error:

```
Encountered error during OAuth token request. 

Additional Data 

Exception details: 
Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthInvalidGrantException: MSIS9453: Received invalid OAuth JWT Bearer request. A problem occurred while creating the user token. Inner exception for details have been logged in the debug log.  ---> System.InvalidOperationException: The in-memory representation of the Device Registration Service was not properly initialized. Please ensure the DRServiceManager was initialized.
   at Microsoft.DeviceRegistration.Utilities.DRServiceManager.GetDevice(X509Certificate2 certificate)
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.CreateUserToken()
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.ValidateJWTBearer()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.ValidateJWTBearer()
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.ValidateCore()
   at Microsoft.IdentityServer.Web.Protocols.ProtocolContext.Validate()
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthTokenProtocolHandler.ProcessJWTBearerRequest(OAuthJWTBearerRequestContext jwtBearerContext)

System.InvalidOperationException: The in-memory representation of the Device Registration Service was not properly initialized. Please ensure the DRServiceManager was initialized.
   at Microsoft.DeviceRegistration.Utilities.DRServiceManager.GetDevice(X509Certificate2 certificate)
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.CreateUserToken()
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.ValidateJWTBearer()
```

ADFS on premise already connected to Azure AD. How resolve this issue? From all docu it seems that token should work withouut Device Registration Service. If service should enabled how to do it without making problems with WAP or Azure?

**Comment by aczechowski** [comment]
@evgenii-spec what Windows client doc are you referencing?

**Comment by aczechowski** [comment]
Thanks @evgenii-spec for taking the time to share this with the Windows documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time - I did a few searches through our content and can't determine what article under Windows client it might be referencing. Feel free to reopen with more information.
