### ISSUE TITLE
Getting Unhandled exception while running Setupdiag

### ISSUE THREAD

**Issue by Sumitdhiman** [MicrosoftDocs/windows-itpro-docs#865]
Object reference not set to an instance of an object.
Exception System.NullReferenceException: Object reference not set to an instance of an object.
Source: SetupDiag
Stack:    at Microsoft.Internal.Deployment.SetupDiag.CSetupDiag.<>c__DisplayClass4_0.<FindParseLatestSetupLog>b__4(CSetupActLog x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Internal.Deployment.SetupDiag.CSetupDiag.FindParseLatestSetupLog(SetupDiagParameters setupDiagParams)
   at Microsoft.Internal.Deployment.SetupDiag.CSetupDiag.RunDiag(String strRulesFile, String strlogsPath, String strMode, String strOutPut, String strFormat, String resLevel, Boolean fCreateLogs)
   at Microsoft.Internal.Deployment.SetupDiag.Program.Main(String[] args)
Can anyone help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag#release-notes)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/setupdiag.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
This seems to be present on some computers but not others. We have a fix and are should have a new version available soon.

**Comment by greg-lindsay** [comment]
QQ: Are you getting this on a system that hasn't been upgraded recently and therefore has no setup logs?  I have a similar issue but it's because I'm just testing the tool on a system that hasn't been upgraded or failed any upgrades.

**Comment by Sumitdhiman** [comment]
I troubleshoot setup log files on the forum sir. 
Unfortunately, the thread would not be publically available until the next 2 days, But I have a link of the files:
https://1drv.ms/f/s!AmZyFonpB2X1kFkt-bcggJebEVUa
Attempt 1 is throwing the unhandled exception error.
 Attempt 2 jut says Setupdiag was unable to find the root cause.

**Comment by greg-lindsay** [comment]
Thanks for providing the logs, we are investigating.

**Comment by greg-lindsay** [comment]
We should have an updated version available soon. The error that is identified in these logs (both the first and second attempt) is:
Error: Found system boot failure post phase: Downlevel,End.
Diagnostic information: BootLogErrorCount: 0, LastErrorEvent: 0, LastErrorCode: 0

I'll try to obtain more information about this for you.

**Comment by greg-lindsay** [comment]
This type of error is rather generic, indicating that the system was unable to boot into SafeOS mode. To troubleshoot this, the recommendation is to boot the system into WinPE (same version as the destination OS). If you are able to boot into WinPE, then attempt to browse files. If you are unable to browse files then 3rd party disk encryption might be an issue. If you are unable to boot into WinPE at all, try booting to a previous version of WinPE. If one works and the other does not, you might have a hardware incompatibility issue, or BIOS verion incompatibility.

**Comment by Sumitdhiman** [comment]
Thank you for your continued response, Greg.
To be honest, I am still training for troubleshooting the logs at the forums. Sometimes my troubleshoot steps hit, sometimes miss :)
A small question for you:
I occasionally see a lot of errors especially doing an upgrade to 1803 like where plugins like adammigrate and CntrtextMig fail to transfer:
```
2018-05-09 17:25:41, Error [0x08085f] MIG MigHost: CMigPluginSurrogate::LoadAndRegisterServerInThreadContext: LoadLibraryExW(C:\$WINDOWS.~BT\NewOS\Windows\system32\IasMigPlugin.dll, LOAD_WITH_ALTERED_SEARCH_PATH) failed gle=0x7e.[gle=0x0000007e]
2018-05-09 17:25:41, Error [0x080863] MIG MigHost: CMigPluginSurrogate::COMGenericThreadingHostThreadProc: LoadAndRegisterServerInThreadContext() failed hr=0x8007007e.[gle=0x0000007e]
2018-05-09 17:25:41, Error [0x0808ff] MIG COutOfProcPluginFactory::CreateInstance: m_currentHostSurrogate->LoadDllServer(C:\$WINDOWS.~BT\NewOS\Windows\system32\IasMigPlugin.dll, {6DF2D9DF-1294-4637-82D3-D53761CA2C11}, 0) failed, hr=[0x8007007e].
2018-05-05 22:36:56, Error      [0x08038d] MIG    Failure while calling IPostApply->ApplySuccess for Plugin={ServerPath="Microsoft-Windows-DirectoryServices-ADAM-Client\adammigrate.dll", CLSID={43CCF250-2A74-48c6-9620-FC312EC475D6}, ThreadingModel=Apartment}. Error: 0x80070002

```

Does this mean an error while transferring these plugins/files or is it related to something else and is generic?

**Comment by greg-lindsay** [comment]
Some additional comments from our developer: 

Unless the plug-in failure is followed by a setup platform message saying it will add an extra error, the plug-in failure will not be a fatal error (won’t cause a rollback).  Below is an example of a fatal plug-in failure because after the plug-in error message, SP adds the “Will add an extra error” message.  That indicates it will be a fatal (cause rollback) error.

2018-05-04 12:32:16, Info                  MIG    IPostApply::ApplySuccess for Plugin={ServerPath="%windir%\system32\migration\TileStoreMigrationPlugin.dll", CLSID={59735225-901B-4A9F-A7B6-52D7D5E0776D}, ThreadingModel=Apartment} - Working directory: C:\$WINDOWS.~BT\Work\MachineIndependent\Working\srcworking\agentmgr\CCSIAgent\005A1F0E\USER00000003
2018-05-04 12:32:18, Info       [0x0808fe] MIG    Plugin {59735225-901B-4A9F-A7B6-52D7D5E0776D}: TileMigration signaling extension thread.
2018-05-04 12:32:18, Info       [0x0808fe] MIG    Plugin {59735225-901B-4A9F-A7B6-52D7D5E0776D}: TileMigration discontinuing plug-in timeout extension.
2018-05-04 12:32:18, Info       [0x0808fe] MIG    Plugin {59735225-901B-4A9F-A7B6-52D7D5E0776D}: TileMigration exiting.
2018-05-04 12:32:18, Error      [0x08038d] MIG    Failure while calling IPostApply->ApplySuccess for Plugin={ServerPath="%windir%\system32\migration\TileStoreMigrationPlugin.dll", CLSID={59735225-901B-4A9F-A7B6-52D7D5E0776D}, ThreadingModel=Apartment}. Error: 0x80070013
2018-05-04 12:32:18, Info                  SP     Will add an extra error
2018-05-04 12:32:18, Error                 SP     Error READ, 0x00000013 while gathering/applying object: apply-success, Action,CMXEPlugin,C:\$WINDOWS.~BT\Work\MachineIndependent\Working\agentmgr\CCSIAgent,%windir%\system32\migration\TileStoreMigrationPlugin.dll,{59735225-901B-4A9F-A7B6-52D7D5E0776D},Apartment. Will return 2[gle=0x000000cb]

**Comment by Sumitdhiman** [comment]
Sometimes finding the cause of the rollback becomes somewhat difficult, so this seems is an interesting piece of information. Thank you :)

**Comment by seamonkey420** [comment]
I've now seen our 1607 to 1803 test upgrades completely fail on 5 machines in a row.  each time we see this error in the setupdiag.exe logs:

Error: SetupDiag reports fatal migration plug-in failure. Plug-in Name = %windir%\system32\IasMigPlugin.dll, Migration Operation = IPostApply->PostApply, Plug-in Error: 0x0000007
Refer to https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-error-codes for error information.

most likely will be putting in an actual premier support ticket. Why can't MS just make Win10 ENTERPRISE Editions running build 1607 - 1709 to be the new LTSB.  IE ENTERPRISE GIVES ZERO EFFS ABOUT FEATURE UPDATES THAT LITERALLY BRING MORE PAIN THAN GOOD.  #LISTENTOYOURADMINS!!
